vectors :
	make -C ../../ MAIN=src/vis/giant-vectors all

vis :
	make -C ../../ MAIN=src/vis/giant-vis all

mini_maps :
	make -C ../../ MAIN=src/vis/giant-mini_maps all

all : 
	make -C ../../ all

.PHONY : all
