vectors :
	make -C ../../ MAIN=src/vis/giant-vectors all

vis :
	make -C ../../ MAIN=src/vis/giant-vis all

vis_data :
	make -C ../../ MAIN=src/vis/giant-vis_data all

mini_maps :
	make -C ../../ MAIN=src/vis/giant-mini_maps all

graph_widgets :
	make -C ../../ MAIN=src/vis/giant-graph_widgets all

all : 
	make -C ../../ all

.PHONY : all
