framework_test :
	make -C ../ MAIN=test/framework_test EXEC=test/framework_test
        
martin_test :
	make -C ../ MAIN=test/martin_test EXEC=test/martin_test

graph_widget :
	make -C ../ MAIN=test/giant_test-graph_widget EXEC=test/graph_widget all
mini_map :
	make -C ../ MAIN=test/giant_test-mini_map EXEC=test/mini_map all

file_management :
	make -C ../ MAIN=test/giant_test-file_management EXEC=test/file_management all

testxml_val :
	make -C ../ MAIN=test/testxml_val EXEC=test/testxml_val all

evolution :
	make -C ../ MAIN=test/giant_test-evolution EXEC=test/evolution all

graphlib :
	make -C ../ MAIN=test/graphlib_test EXEC=test/graphlib_test all

matrix_layouts :
	make -C ../ MAIN=test/matrix_layouts_test EXEC=test/matrix_layouts_test all

layout_factory :
	make -C ../ MAIN=test/layout_factory_test EXEC=test/layout_factory_test all

all:
	make -C ../ all

.PHONY : framework_test martin_test mini_map graph_widget evolution
