mini_map :
	make -C ../ MAIN=test/giant_test-mini_map EXEC=test/mini_map all

file_management :
	make -C ../ MAIN=test/giant_test-file_management EXEC=test/file_management all

evolution :
	make -C ../ MAIN=test/giant_test-evolution EXEC=test/evolution all

graph_lib :
	make -C ../ MAIN=test/giant_test-graph_lib EXEC=test/graph_lib all

all:
	make -C ../ all

