fixed_priority_queues :
	make -C ../../ MAIN=src/utils/giant-fixed_priority_queues all

evolutions :
	make -C ../../ MAIN=src/utils/giant-evolutions all

tasking_test :
	make -C ../../ MAIN=src/utils/tasking_test EXEC=tasking_test all

all : 
	make -C ../../ all

.PHONY : all
