simple_priority_queues :
	make -C ../../ MAIN=src/utils/giant-simple_priority_queues all

fixed_priority_queues :
	make -C ../../ MAIN=src/utils/giant-fixed_priority_queues all

evolutions :
	make -C ../../ MAIN=src/utils/giant-evolutions all

all : 
	make -C ../../ all

.PHONY : all
